dockerize dlnr_status telegram bot
Egorrko/dlnr_status pull request #1
Opened 2022-02-22 17:32 UTC by ovosh000

2022-02-22 20:00 UTC, Egorrko requested changes

2022-02-22 20:00 UTC, Egorrko commented on Dockerfile
> +RUN pip install -r requirements.txt
Нужно сначала ставить пакеты, а потом копировать код. Так быстрее.
https://habr.com/ru/company/itsumma/blog/501680/

2022-02-22 20:06 UTC, Egorrko commented on docker-compose.yml
> +version: '2'
А почему версия такая низкая? Нельзя взять самую последнюю?

2022-02-23 03:40 UTC, ovosh000 commented on docker-compose.yml
> +version: '2'
Обновил до 3.9

2022-02-23 08:12 UTC, merged